#!/bin/bash

echo "========================================"
echo "SETUP INSTRUCTIONS"
echo "========================================"
echo ""
echo "1. Install Supabase SSR Package:"
echo "   npm install @supabase/ssr"
echo ""
echo "2. Run this SQL in Supabase SQL Editor:"
echo "   https://app.supabase.com/project/lzpyfvqdimkrkioxrzbf/sql"
echo ""
echo "========================================"
cat /workspaces/CivicOPIndia/supabase/migrations/003_activity_likes.sql
echo "========================================"
echo ""
echo "FEATURES ADDED:"
echo "✅ Admin session persists until manual logout"
echo "✅ Edit and Delete buttons for all activities"
echo "✅ IP-based like tracking (prevents multiple likes)"
echo "✅ Like tracking table created"
echo ""
echo "After running the SQL, restart the server with: npm run dev"
echo "========================================"
