name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    runs-on: ubuntu-latest
    if: ${{ secrets.SUPABASE_URL && secrets.SUPABASE_SERVICE_ROLE_KEY && env.RUN_INTEGRATION == 'true' }}
    env:
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start Next Dev
        run: npm run dev & npx wait-on http://localhost:3000
      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.ts
